#!/usr/bin/env bash
# This is a Bash completion script
# It should be placed in /etc/bash_completion.d/
# If you intall timertab from the AUR, that will be done automatically

abs_path="/usr/bin/timertab"

_script() {
    local cur commands
    commands=$($abs_path list_opts)
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=()
    COMPREPLY=( $(compgen -W "${commands}" -- ${cur}) )

    return 0
}

complete -o nospace -F _script timertab
